services:
    bugsnag.client:
        class: %bugsnag.client%
        arguments: [%bugsnag.api_key%]
        calls:
            - [setReleaseStage, ['%kernel.environment%']]
            - [setNotifyReleaseStages, ['%bugsnag.notify_stages%']]
            - [setProxySettings, ['%bugsnag.proxy%']]
            - [setAppVersion, ['%bugsnag.app_version%']]

    bugsnag.exception_listener:
        class: %bugsnag.exception_listener%
        arguments: ["@bugsnag.client"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    bugsnag.shutdown_listener:
        class: %bugsnag.shutdown_listener%
        arguments: ["@bugsnag.client"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: register }
